import {installClearance} from './camera-clearance.js';
import{createSky}from'./sky.js';
import * as THREE from '../assets/three.module.js';
// Small self-contained WebGL renderer. No CDN or runtime dependencies.
export const M={
 identity:()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1],
 mul:(a,b)=>{let o=new Array(16).fill(0);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;},
 transform(x=0,y=0,z=0,ry=0,rx=0,rz=0,s=1){let a=this.identity();a[0]=Math.cos(ry)*s;a[2]=-Math.sin(ry)*s;a[8]=Math.sin(ry)*s;a[10]=Math.cos(ry)*s;a[5]=s;a[12]=x;a[13]=y;a[14]=z;if(rx){let b=this.identity();b[5]=b[10]=Math.cos(rx);b[6]=Math.sin(rx);b[9]=-Math.sin(rx);a=this.mul(a,b);}if(rz){let b=this.identity();b[0]=b[5]=Math.cos(rz);b[1]=Math.sin(rz);b[4]=-Math.sin(rz);a=this.mul(a,b);}return a;},
 perspective:(f,a,n,z)=>{let t=1/Math.tan(f/2);return[t/a,0,0,0,0,t,0,0,0,0,(z+n)/(n-z),-1,0,0,2*z*n/(n-z),0];},
 look(eye,target){let norm=a=>{let d=Math.hypot(...a);return a.map(x=>x/d);},cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);let z=norm(eye.map((v,i)=>v-target[i])),x=norm(cross([0,1,0],z)),y=cross(z,x);return[x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1];}
};
export function color(s){if(Array.isArray(s))return s;let n=parseInt(s.replace('#',''),16);return[(n>>16)/255,((n>>8)&255)/255,(n&255)/255];}
export class Geometry{
 constructor(){this.data=[];}
 vertex(p,n,c){this.data.push(...p,...n,...color(c));}
 tri(a,b,c,n,col){this.vertex(a,n,col);this.vertex(b,n,col);this.vertex(c,n,col);return this;}
 box(x,y,z,w,h,d,col){let X=[x-w/2,x+w/2],Y=[y-h/2,y+h/2],Z=[z-d/2,z+d/2];let pts=[[X[0],Y[0],Z[0]],[X[1],Y[0],Z[0]],[X[1],Y[1],Z[0]],[X[0],Y[1],Z[0]],[X[0],Y[0],Z[1]],[X[1],Y[0],Z[1]],[X[1],Y[1],Z[1]],[X[0],Y[1],Z[1]]];[[0,3,2,1,0,0,-1],[4,5,6,7,0,0,1],[0,4,7,3,-1,0,0],[1,2,6,5,1,0,0],[3,7,6,2,0,1,0],[0,1,5,4,0,-1,0]].forEach(f=>{let n=f.slice(4);this.tri(pts[f[0]],pts[f[1]],pts[f[2]],n,col);this.tri(pts[f[0]],pts[f[2]],pts[f[3]],n,col);});return this;}
 sphere(x,y,z,rx,ry,rz,col,segs=12,rings=8){const point=(a,b)=>{let n=[Math.sin(b)*Math.cos(a),Math.cos(b),Math.sin(b)*Math.sin(a)];return {p:[x+n[0]*rx,y+n[1]*ry,z+n[2]*rz],n};};for(let i=0;i<rings;i++)for(let j=0;j<segs;j++){let a=j/segs*Math.PI*2,b=i/rings*Math.PI,c=(j+1)/segs*Math.PI*2,d=(i+1)/rings*Math.PI;let p=[point(a,b),point(c,b),point(c,d),point(a,d)];for(let k of[0,1,2,0,2,3])this.vertex(p[k].p,p[k].n,col);}return this;}
 cylinder(x,y,z,r,h,col,segs=12){for(let i=0;i<segs;i++){let a=i/segs*Math.PI*2,b=(i+1)/segs*Math.PI*2,na=[Math.cos(a),0,Math.sin(a)],nb=[Math.cos(b),0,Math.sin(b)],p=[x+r*na[0],y-h/2,z+r*na[2]],q=[x+r*nb[0],y-h/2,z+r*nb[2]],u=[p[0],y+h/2,p[2]],v=[q[0],y+h/2,q[2]];this.vertex(p,na,col);this.vertex(u,na,col);this.vertex(v,nb,col);this.vertex(p,na,col);this.vertex(v,nb,col);this.vertex(q,nb,col);this.tri([x,y+h/2,z],v,u,[0,1,0],col);this.tri([x,y-h/2,z],p,q,[0,-1,0],col);}return this;}
 torus(x,y,z,r,t,col,axis='x',segs=20){const p=(a,b)=>{let q=[t*Math.sin(b),(r+t*Math.cos(b))*Math.cos(a),(r+t*Math.cos(b))*Math.sin(a)],n=[Math.sin(b),Math.cos(b)*Math.cos(a),Math.cos(b)*Math.sin(a)];if(axis==='z'){q=[q[1],q[2],q[0]];n=[n[1],n[2],n[0]];}if(axis==='y'){q=[q[1],q[0],q[2]];n=[n[1],n[0],n[2]];}return{p:[x+q[0],y+q[1],z+q[2]],n};};for(let i=0;i<segs;i++)for(let j=0;j<6;j++){let pts=[p(i/segs*6.283,j/6*6.283),p((i+1)/segs*6.283,j/6*6.283),p((i+1)/segs*6.283,(j+1)/6*6.283),p(i/segs*6.283,(j+1)/6*6.283)];for(let k of[0,1,2,0,2,3])this.vertex(pts[k].p,pts[k].n,col);}return this;}
 segment(a,b,r,col){let mid=a.map((v,i)=>(v+b[i])/2),v=b.map((n,i)=>n-a[i]),h=Math.hypot(...v),g=new Geometry().cylinder(0,0,0,r,h,col);let y=v.map(n=>n/h),tmp=Math.abs(y[1])>.95?[1,0,0]:[0,1,0],cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],xx=cross(tmp,y),l=Math.hypot(...xx),xxn=xx.map(n=>n/l),zz=cross(xxn,y),m=[...xxn,0,...y,0,...zz,0,...mid,1];this.merge(g,m);return this;}
 merge(g,m=M.identity()){for(let i=0;i<g.data.length;i+=9){let p=g.data.slice(i,i+3),n=g.data.slice(i+3,i+6),q=[0,1,2].map(j=>m[j]*p[0]+m[4+j]*p[1]+m[8+j]*p[2]+m[12+j]),nn=[0,1,2].map(j=>m[j]*n[0]+m[4+j]*n[1]+m[8+j]*n[2]);this.vertex(q,nn,g.data.slice(i+6,i+9));}return this;}
}
export class Renderer{
 curveMaterial(material){
  if(material.userData.arielCurve)return;material.userData.arielCurve=true;
  this.curveUniform??={value:0};const uniform=this.curveUniform;this.clearanceUniform??={value:0};const clearance=this.clearanceUniform;
  material.onBeforeCompile=shader=>{shader.uniforms.arielDistance=uniform;shader.vertexShader='uniform float arielDistance;\nfloat cityPath(float d){return 9.0*sin(d/120.0)+4.0*sin(d/70.0);}\n'+shader.vertexShader;shader.vertexShader=shader.vertexShader.replace('#include <project_vertex>',THREE.ShaderChunk.project_vertex.replace('mvPosition = modelViewMatrix * mvPosition;','float d=arielDistance; float tangent=0.075*cos(d/120.0)+(4.0/70.0)*cos(d/70.0); mvPosition.x += cityPath(d-mvPosition.z)-cityPath(d)+mvPosition.z*tangent; mvPosition = modelViewMatrix * mvPosition;'));shader.vertexShader=shader.vertexShader.replace('#include <worldpos_vertex>',THREE.ShaderChunk.worldpos_vertex.replace('worldPosition = modelMatrix * worldPosition;', 'float wd=arielDistance; float wt=0.075*cos(wd/120.0)+(4.0/70.0)*cos(wd/70.0); worldPosition.x += cityPath(wd-worldPosition.z)-cityPath(wd)+worldPosition.z*wt; worldPosition = modelMatrix * worldPosition;'));installClearance(shader,clearance);};material.customProgramCacheKey=()=> 'ariel-continuous-road-clearance-v3';
 }
 constructor(canvas){this.cutawayEnabled=true;this.clearanceUniform={value:0};this.canvas=canvas;this.webgl=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.lowQuality=(navigator.hardwareConcurrency||4)<=4||innerWidth<600;this.webgl.info.autoReset=false;this.webgl.setPixelRatio(Math.min(devicePixelRatio||1,this.lowQuality?1:1.5));this.webgl.shadowMap.enabled=!this.lowQuality;this.webgl.shadowMap.type=THREE.PCFSoftShadowMap;this.webgl.toneMapping=THREE.ACESFilmicToneMapping;this.webgl.toneMappingExposure=.95;this.scene=new THREE.Scene();this.sky=createSky(this.scene);this.skyTime=0;this._drawMatrix=new THREE.Matrix4();this.camera=new THREE.PerspectiveCamera(55,1,.1,440);this.scene.fog=new THREE.Fog('#a7a091',38,142);this.ambient=new THREE.HemisphereLight('#dbe9ec','#676248',2.1);this.scene.add(this.ambient);this.sun=new THREE.DirectionalLight('#ffe0a9',3.0);this.sun.position.set(-12,24,8);this.sun.castShadow=true;this.sun.shadow.mapSize.set(1024,1024);Object.assign(this.sun.shadow.camera,{left:-17,right:17,top:25,bottom:-25,near:.5,far:70});this.sun.shadow.bias=-.0008;this.sun.shadow.normalBias=.025;this.sun.target.position.set(0,0,-12);this.scene.add(this.sun,this.sun.target);const fill=new THREE.DirectionalLight('#8fa6ba',.5);fill.position.set(10,8,-10);this.scene.add(fill);this.meshes=new Set();this.materials=new Map();this.textures=new Map();}
 mesh(geo){let geometry=new THREE.BufferGeometry(),data=new Float32Array(geo.data),buffer=new THREE.InterleavedBuffer(data,9);geometry.setAttribute('position',new THREE.InterleavedBufferAttribute(buffer,3,0));geometry.setAttribute('normal',new THREE.InterleavedBufferAttribute(buffer,3,3));geometry.setAttribute('color',new THREE.InterleavedBufferAttribute(buffer,3,6));geometry.computeBoundingSphere();let mesh={geometry,pool:[],used:0,count:data.length/9};if(geo.uv){geometry.setAttribute('uv',new THREE.Float32BufferAttribute(geo.uv,2));if(!this.textures.has(geo.map)){let texture=new THREE.TextureLoader().load(geo.map);texture.colorSpace=THREE.SRGBColorSpace;this.textures.set(geo.map,texture);}mesh.material=new THREE.MeshStandardMaterial({map:this.textures.get(geo.map),roughness:.93,side:THREE.FrontSide,transparent:false,depthTest:true,depthWrite:true});}this.meshes.add(mesh);return mesh;}
 free(mesh){mesh.pool.forEach(x=>{this.scene.remove(x);x.customDepthMaterial?.dispose();});mesh.geometry.dispose();mesh.material?.dispose();this.meshes.delete(mesh);}
 begin(eye,target,rain=0){if(this.curveUniform)this.curveUniform.value=this.routeDistance||0;let w=this.canvas.clientWidth,h=this.canvas.clientHeight;if(this.width!==w||this.height!==h){this.width=w;this.height=h;this.webgl.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}this.camera.position.set(...eye);this.camera.lookAt(...target);let c=new THREE.Color('#b7ab97').lerp(new THREE.Color('#526777'),rain);this.scene.background=c;this.scene.fog.color.copy(c);this.sun.intensity=2.2-rain*1.6;this.ambient.intensity=1.7-rain*.3;for(let m of this.meshes){m.used=0;for(let o of m.pool){o.visible=false;o.count=0;}}}
 environment(profile,night,rain,dt){
  const mix=1-Math.exp(-Math.max(0,dt)*1.5),c=(day,dark)=>new THREE.Color(day).lerp(new THREE.Color(dark),night);
  const sky=c(profile.sky||'#b7ab97',profile.nightSky||profile.night||'#122039').lerp(new THREE.Color(profile.rainSky||'#526777'),rain*.55);
  const fog=c(profile.fog||profile.sky||'#b7ab97',profile.nightSky||profile.night||'#14223c').lerp(new THREE.Color(profile.rainSky||'#526777'),rain*.55);
  if(!this.env){this.env={sky:sky.clone(),fog:fog.clone(),sun:2.2,ambient:1.7};}
  this.env.sky.lerp(sky,mix);this.env.fog.lerp(fog,mix);this.env.sun+=((profile.sunIntensity??2.2)*(1-night*.85)*(1-rain*.65)-this.env.sun)*mix;this.env.ambient+=((profile.ambientIntensity??1.7)*(1-night*.32)-this.env.ambient)*mix;
  this.skyTime+=dt;this.sky.update(this.camera,this.env.sky,night,rain,this.skyTime);this.scene.background.copy(this.env.sky);this.scene.fog.color.copy(this.env.fog);this.scene.fog.near=profile.fogNear??160;this.scene.fog.far=profile.fogFar??425;
  this.sun.color.lerp(c(profile.sunColor||profile.sun||'#ffe0a9','#c5d4ff'),mix);this.sun.intensity=this.env.sun;
  this.ambient.color.lerp(c(profile.ambientColor||'#dbe9ec','#718bce'),mix);this.ambient.groundColor.lerp(c(profile.groundColor||profile.ground||'#676248','#293752'),mix);this.ambient.intensity=this.env.ambient;
 }
 label(text){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=96;const c=canvas.getContext('2d');c.fillStyle='#11282d';c.fillRect(0,0,512,96);c.fillStyle='#ffe8ae';c.font='bold 40px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,48);const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;this.textures.set('bus-sign',texture);const mesh={geometry:new THREE.PlaneGeometry(1.6,.30),pool:[],used:0,material:new THREE.MeshBasicMaterial({map:texture,depthTest:true,depthWrite:true})};this.meshes.add(mesh);return mesh;}
 draw(mesh,model=M.identity(),glow=0){const key=String(glow);if(!this.materials.has(key))this.materials.set(key,new THREE.MeshStandardMaterial({vertexColors:true,roughness:.88,metalness:.025,side:THREE.DoubleSide,emissive:'#b9d99b',emissiveIntensity:glow*.5}));const index=mesh.used++,batch=Math.floor(index/128),slot=index%128;let o=mesh.pool[batch];if(!o){const material=mesh.material||this.materials.get(key);this.curveMaterial(material);o=new THREE.InstancedMesh(mesh.geometry,material,128);o.customDepthMaterial=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking});this.curveMaterial(o.customDepthMaterial);o.instanceMatrix.setUsage(THREE.DynamicDrawUsage);o.castShadow=mesh.castShadow!==false;o.receiveShadow=true;o.frustumCulled=true;o.boundingSphere=new THREE.Sphere(new THREE.Vector3(0,25,-160),370);mesh.pool.push(o);this.scene.add(o);}const material=mesh.material||this.materials.get(key);this.curveMaterial(material);if(o.material!==material)o.material=material;o.visible=true;o.count=slot+1;o.setMatrixAt(slot,this._drawMatrix.fromArray(model));}
 async prepare(onProgress=()=>{}){
  const started=performance.now(),warm=new THREE.Matrix4().makeTranslation(0,-1000,-1000).elements;
  this.begin([0,4,8],[0,1,-10]);
  for(const mesh of this.meshes)for(let i=0;i<(mesh.prewarmInstances||1);i++)this.draw(mesh,warm);
  onProgress('Preparando materiales');
  const textures=new Set();this.scene.traverse(o=>{for(const m of [].concat(o.material||[])){for(const value of Object.values(m))if(value?.isTexture)textures.add(value);for(const u of Object.values(m.uniforms||{}))if(u.value?.isTexture)textures.add(u.value);}});
  for(const texture of textures)if(texture.image?.width||texture.isDataTexture)this.webgl.initTexture(texture);
  await this.webgl.compileAsync(this.scene,this.camera);
  onProgress('Preparando la primera partida');this.end();
  this.preparation={milliseconds:performance.now()-started,pools:[...this.meshes].reduce((sum,m)=>sum+m.pool.length,0),textures:textures.size,geometries:this.webgl.info.memory.geometries};
  await new Promise(resolve=>requestAnimationFrame(resolve));
 }
 end(){this.webgl.info.reset();for(const m of this.meshes)for(const o of m.pool)if(o.count)o.instanceMatrix.needsUpdate=true;this.webgl.render(this.scene,this.camera);}
}

